before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq wget cmake gcc bash libboost-test-dev nodejs python-pip python-dev
        # Make sure we use the latest cmake
        - sudo pip install virtualenv -q
        - (cd /tmp && wget http://www.cmake.org/files/v3.1/cmake-3.1.3.tar.gz && tar zxf cmake-3.1.3.tar.gz)
        - (cd /tmp/cmake-3.1.3 && cmake . && make && sudo make install) > /dev/null 2>&1

script: "./test/test.sh"
